# Generated by Django 4.0.3 on 2022-07-17 08:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='actualizado',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='curso',
            name='creado',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
